// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0wQsz32SA58zRv3B_hFLZd7rh4qwCACs',
    appId: '1:446511636551:web:9954c68664be758afb5162',
    messagingSenderId: '446511636551',
    projectId: 'chat-app-firebase-ee82c',
    authDomain: 'chat-app-firebase-ee82c.firebaseapp.com',
    storageBucket: 'chat-app-firebase-ee82c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALBc1dnN18eRTI24y1sk8FeuSHknoYmos',
    appId: '1:446511636551:android:6a85724b7131d666fb5162',
    messagingSenderId: '446511636551',
    projectId: 'chat-app-firebase-ee82c',
    storageBucket: 'chat-app-firebase-ee82c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJus409ubA2LZ6iNrfbGDvQiC3FzVg5I',
    appId: '1:446511636551:ios:e18bd4b42186ec9dfb5162',
    messagingSenderId: '446511636551',
    projectId: 'chat-app-firebase-ee82c',
    storageBucket: 'chat-app-firebase-ee82c.appspot.com',
    iosClientId: '446511636551-ddpm07tbleua3o5ulkp84a44pchb34ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQJus409ubA2LZ6iNrfbGDvQiC3FzVg5I',
    appId: '1:446511636551:ios:e18bd4b42186ec9dfb5162',
    messagingSenderId: '446511636551',
    projectId: 'chat-app-firebase-ee82c',
    storageBucket: 'chat-app-firebase-ee82c.appspot.com',
    iosClientId: '446511636551-ddpm07tbleua3o5ulkp84a44pchb34ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );
}
